/** @format */

export const GET_DATA = "GET_DATA";
export const FILTER_MOVIE_BY_GENRE = "FILTER_MOVIE_BY_GENRE";
export const FILTER_MOVIE_BY_LANGUAGE = "FILTER_MOVIE_BY_LANGUAGE";
export const FILTER_MOVIE_BY_THEATER = "FILTER_MOVIE_BY_THEATER";
